- name: Integration test for Docker Image
  connection: local
  hosts: localhost

  tasks:
    - name: Display message
      debug:
        msg: "Success"
    - name: Create ENV Varibale
      shell: echo "ANSIBLE_TEST=$(echo Success)" >> $GITHUB_ENV
