apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "ansible-runner" .Values.configmap.name }}
  namespace: {{ default "default" .Values.namespace }}
data:
  {{ default "ansible-runner" .Values.configmap.name }}.yml: {{ .Values.playbook | quote }}