apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ansible-runner
    namespace: default
  data:
    ansible-runner.yml: |
      - name: Integration test for Docker Image
        connection: local
        hosts: localhost
        
        tasks:
          - name: Display message
            debug:
              msg: "Success"