apiVersion: v1
kind: Pod
metadata:
  name: $
  namespace: default
spec:
  containers:
    - name: ${GITHUB_REPOSITORY#*/}
      image: k3d-${GITHUB_REPOSITORY#*/}.localhost:12345/${GITHUB_REPOSITORY#*/}:testing
      args:
        - ${GITHUB_REPOSITORY#*/}.yml
      volumeMounts:
        - name: ${GITHUB_REPOSITORY#*/}
          mountPath: /ansible
  volumes:
    - name: ${GITHUB_REPOSITORY#*/}
      configMap:
        name: ${GITHUB_REPOSITORY#*/}