apiVersion: v1
kind: Pod
metadata:
  name: {{ default "ansible-runner"  .Values.name }}
  namespace: {{ default "default"  .Values.namespace }}
  labels:
    app: {{ default "ansible-runner"  .Values.name }}
spec:
  containers:
    - name: {{ default "ansible-runner"  .Values.name }}
      image: {{ default "ishanjainn/ansible-runner" .Values.image.repository }}:{{ default (include "argo-cd.defaultTag" .) .Values.image.tag }}
      args:
        - {{ default "ansible-runner" .Values.configmap.name }}.yml
      volumeMounts:
        - name: {{ default "ansible-runner"  .Values.configmap.name }}
          mountPath: /ansible
  volumes:
    - name: {{ default "ansible-runner"  .Values.configmap.name }}
      configMap:
        name: {{ default "ansible-runner"  .Values.configmap.name }}
