name: Docker

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: "cat package.json"
        run: cat ./package.json
      - run: git stash
      - run: npm version patch
      - name: "cat package.json"
        run: cat ./package.json
#      - name: "cat package.json"
#        run: cat ./package.json
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Log into registry ${{ env.REGISTRY }}
#        uses: docker/login-action@v1
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: ./docker
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ env.IMAGE_NAME }}:latest, ${{ env.IMAGE_NAME }}:0.${{ github.run_number }}
