name: Renovate

on:
  schedule:
    - cron: '0/15 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.71.3
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
