name: Renovate
on:
  push:
    branches: [ main ]
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.68.0
        with:
          configurationFile: renovate-config.json
          token: 'x-access-token:${{ steps.get_token.outputs.app_token }}'